import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const auth = {
  signInWithOAuth: async (
    provider: "google" | "apple" | "azure",
    opts?: SignInOptions
  ) => {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo: opts?.redirect_uri,
        queryParams: opts?.extraParams,
      },
    });

    if (error) {
      return { error };
    }

    return { data };
  },

  signOut: async () => {
    return await supabase.auth.signOut();
  },

  getSession: async () => {
    return await supabase.auth.getSession();
  },

  getUser: async () => {
    return await supabase.auth.getUser();
  },
};

// // This file is auto-generated by Lovable. Do not modify it.

// import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
// import { supabase } from "../supabase/client";
// const lovableAuth = createLovableAuth();

// type SignInOptions = {
//   redirect_uri?: string;
//   extraParams?: Record<string, string>;
// };

// export const lovable = {
//   auth: {
//     signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
//       const result = await lovableAuth.signInWithOAuth(provider, {
//         redirect_uri: opts?.redirect_uri,
//         extraParams: {
//           ...opts?.extraParams,
//         },
//       });

//       if (result.redirected) {
//         return result;
//       }

//       if (result.error) {
//         return result;
//       }

//       try {
//         await supabase.auth.setSession(result.tokens);
//       } catch (e) {
//         return { error: e instanceof Error ? e : new Error(String(e)) };
//       }
//       return result;
//     },
//   },
// };